# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-19 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelyPropertiesapp', '0003_auto_20180119_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelyproperties',
            name='booked_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homelyproperties',
            name='booked_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
