# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-19 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homelyPropertiesapp', '0004_auto_20180119_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelyproperties',
            name='booked_from',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homelyproperties',
            name='booked_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homelyproperties',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
